language: ruby

rvm:
  - 2.0.0
  - 2.1.5
  - 2.2.2
  - 2.3.0
  - rbx

install: bundle install --retry=3

addons:
  code_climate:
    repo_token: 130f102bb847552a17b84646d50dba4809adf2af84aff06d8413dbe4d79ce8c0